server:
  tomcat:
    accept-count: 300
  port: 8080

spring:
  aop:
    auto: true
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cardinity_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true


application:
  request-id-header: request-id
  token-expiry-minute: 30
  token-prefix: Bearer
  jwt-secret: dipAnj@L
  auth-header-name: Authorization
  token-validation-regex: ^Bearer\s[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$
  seeder-enabled: true
